---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "install nodejs environment"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Remove dependencies that are no longer required"
  become: true
  apt:
    autoremove: yes